ARG NODE_VERSION

FROM node:${NODE_VERSION}-alpine AS base

############################################ DEPENDENCIES #######################################################
FROM base AS deps
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY --link prisma/enum-generator.cjs ./prisma/enum-generator.cjs
COPY --link prisma ./
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml\* ./
RUN \
    if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
    elif [ -f package-lock.json ]; then npm ci; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && exit 1; \
    fi

RUN npx prisma generate
COPY --link prisma/enums.ts ./prisma/enums.ts
COPY --link . .

################################################## DEV  ###########################################################
FROM base AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .


################################################# BUILDER  #########################################################
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
RUN \
    if [ -f yarn.lock ]; then SKIP_ENV_VALIDATION=1 yarn build; \
    elif [ -f package-lock.json ]; then SKIP_ENV_VALIDATION=1 npm run build; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && SKIP_ENV_VALIDATION=1 pnpm run build; \
    else echo "Lockfile not found." && exit 1; \
    fi

################################################### RUNNER ###########################################################
FROM gcr.io/distroless/nodejs20-debian12 AS runner
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000 5555

CMD ["node","server.js"]







