// This file was generated by a custom prisma generator, do not edit manually.
export const CredentialDeviceTypeEnum = {
  SINGLE_DEVICE: "Single device",
  MULTI_DEVICE: "Multiple device",
} as const;

export type CredentialDeviceTypeEnum = (typeof CredentialDeviceTypeEnum)[keyof typeof CredentialDeviceTypeEnum];

export const MemberStatusEnum = {
  ACTIVE: "Active",
  PENDING: "Pending",
  INACTIVE: "Inactive",
} as const;

export type MemberStatusEnum = (typeof MemberStatusEnum)[keyof typeof MemberStatusEnum];

export const StakeholderTypeEnum = {
  INDIVIDUAL: "Individual",
  INSTITUTION: "Institution",
} as const;

export type StakeholderTypeEnum = (typeof StakeholderTypeEnum)[keyof typeof StakeholderTypeEnum];

export const StakeholderRelationshipEnum = {
  ADVISOR: "Advisor",
  BOARD_MEMBER: "Board Member",
  CONSULTANT: "Consultant",
  EMPLOYEE: "Employee",
  EX_ADVISOR: "Ex-Advisor",
  EX_CONSULTANT: "Ex-Consultant",
  EX_EMPLOYEE: "Ex-Employee",
  EXECUTIVE: "Executive",
  FOUNDER: "Founder",
  INVESTOR: "Investor",
  NON_US_EMPLOYEE: "Non-US Employee",
  OFFICER: "Officer",
  OTHER: "Other",
} as const;

export type StakeholderRelationshipEnum = (typeof StakeholderRelationshipEnum)[keyof typeof StakeholderRelationshipEnum];

export const ShareTypeEnum = {
  COMMON: "Common",
  PREFERRED: "Preferred",
} as const;

export type ShareTypeEnum = (typeof ShareTypeEnum)[keyof typeof ShareTypeEnum];

export const SharePrefixEnum = {
  CS: "Common shares",
  PS: "Preferred shares",
} as const;

export type SharePrefixEnum = (typeof SharePrefixEnum)[keyof typeof SharePrefixEnum];

export const ConversionRightsEnum = {
  CONVERTS_TO_FUTURE_ROUND: "Converts to future round",
  CONVERTS_TO_SHARE_CLASS_ID: "Converts to share class ID",
} as const;

export type ConversionRightsEnum = (typeof ConversionRightsEnum)[keyof typeof ConversionRightsEnum];

export const CancellationBehaviorEnum = {
  RETIRE: "Retire",
  RETURN_TO_POOL: "Return to pool",
  HOLD_AS_CAPITAL_STOCK: "Hold as capital stock",
  DEFINED_PER_PLAN_SECURITY: "Defined per plan security",
} as const;

export type CancellationBehaviorEnum = (typeof CancellationBehaviorEnum)[keyof typeof CancellationBehaviorEnum];

export const FieldTypes = {
  TEXT: "Text",
  RADIO: "Radio",
  EMAIL: "Email",
  DATE: "Date",
  DATETIME: "Datetime",
  TEXTAREA: "Text Area",
  CHECKBOX: "Checkbox",
  SIGNATURE: "Signature",
  SELECT: "Select",
} as const;

export type FieldTypes = (typeof FieldTypes)[keyof typeof FieldTypes];

export const TemplateStatus = {
  DRAFT: "Draft",
  COMPLETE: "Complete",
} as const;

export type TemplateStatus = (typeof TemplateStatus)[keyof typeof TemplateStatus];

export const EsignRecipientStatus = {
  SENT: "Sent",
  SIGNED: "Signed",
  PENDING: "Pending",
} as const;

export type EsignRecipientStatus = (typeof EsignRecipientStatus)[keyof typeof EsignRecipientStatus];

export const SecuritiesStatusEnum = {
  ACTIVE: "Active",
  DRAFT: "Draft",
  SIGNED: "Signed",
  PENDING: "Pending",
} as const;

export type SecuritiesStatusEnum = (typeof SecuritiesStatusEnum)[keyof typeof SecuritiesStatusEnum];

export const VestingScheduleEnum = {
  VESTING_0_0_0: "Immediate vesting",
  VESTING_0_0_1: "1 year cliff with no vesting",
  VESTING_4_1_0: "4 years vesting every month with no cliff",
  VESTING_4_1_1: "4 years vesting every month with 1 year cliff",
  VESTING_4_3_1: "4 years vesting every 3 months with 1 year cliff",
  VESTING_4_6_1: "4 years vesting every 6 months with 1 year cliff",
  VESTING_4_12_1: "4 years vesting every year with 1 year cliff",
} as const;

export type VestingScheduleEnum = (typeof VestingScheduleEnum)[keyof typeof VestingScheduleEnum];

export const ShareLegendsEnum = {
  US_SECURITIES_ACT: "US Securities Act of 1933",
  SALE_AND_ROFR: "Sale and Right of first refusal",
  TRANSFER_RESTRICTIONS: "Bylaw transfer restrictions",
} as const;

export type ShareLegendsEnum = (typeof ShareLegendsEnum)[keyof typeof ShareLegendsEnum];

export const OptionTypeEnum = {
  ISO: "Incentive Stock Options",
  NSO: "Non-satutory Stock Options",
  RSU: "Restricted Stock Units",
} as const;

export type OptionTypeEnum = (typeof OptionTypeEnum)[keyof typeof OptionTypeEnum];

export const OptionStatusEnum = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  EXERCISED: "Exercised",
  EXPIRED: "Expired",
  CANCELLED: "Cancelled",
} as const;

export type OptionStatusEnum = (typeof OptionStatusEnum)[keyof typeof OptionStatusEnum];

export const SafeTypeEnum = {
  PRE_MONEY: "Pre-Money",
  POST_MONEY: "Post-Money",
} as const;

export type SafeTypeEnum = (typeof SafeTypeEnum)[keyof typeof SafeTypeEnum];

export const SafeStatusEnum = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  PENDING: "Pending",
  EXPIRED: "Expired",
  CANCELLED: "Cancelled",
} as const;

export type SafeStatusEnum = (typeof SafeStatusEnum)[keyof typeof SafeStatusEnum];

export const SafeTemplateEnum = {
  POST_MONEY_CAP: "Valuation Cap, no Discount",
  POST_MONEY_DISCOUNT: "Discount, no Valuation Cap",
  POST_MONEY_MFN: "MFN, no Valuation Cap, no Discount",
  POST_MONEY_CAP_WITH_PRO_RATA: "Valuation Cap, no Discount, include Pro Rata Rights",
  POST_MONEY_DISCOUNT_WITH_PRO_RATA: "Discount, no Valuation Cap, include Pro Rata Rights",
  POST_MONEY_MFN_WITH_PRO_RATA: "MFN, no Valuation Cap, no Discount, include Pro Rata Rights",
  CUSTOM: "Custom",
} as const;

export type SafeTemplateEnum = (typeof SafeTemplateEnum)[keyof typeof SafeTemplateEnum];

export const ConvertibleStatusEnum = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  PENDING: "Pending",
  EXPIRED: "Expired",
  CANCELLED: "Cancelled",
} as const;

export type ConvertibleStatusEnum = (typeof ConvertibleStatusEnum)[keyof typeof ConvertibleStatusEnum];

export const ConvertibleTypeEnum = {
  CCD: "Compulsory Convertible Debenture",
  OCD: "Optionally Convertible Debenture",
  NOTE: "Simple Convertible note",
} as const;

export type ConvertibleTypeEnum = (typeof ConvertibleTypeEnum)[keyof typeof ConvertibleTypeEnum];

export const ConvertibleInterestMethodEnum = {
  SIMPLE: "Simple",
  COMPOUND: "Compound",
} as const;

export type ConvertibleInterestMethodEnum = (typeof ConvertibleInterestMethodEnum)[keyof typeof ConvertibleInterestMethodEnum];

export const ConvertibleInterestAccrualEnum = {
  DAILY: "Daily",
  MONTHLY: "Monthly",
  SEMI_ANNUALLY: "Semi-annually",
  ANNUALLY: "Annually",
  YEARLY: "Yearly",
  CONTINUOUSLY: "Continuously",
} as const;

export type ConvertibleInterestAccrualEnum = (typeof ConvertibleInterestAccrualEnum)[keyof typeof ConvertibleInterestAccrualEnum];

export const ConvertibleInterestPaymentScheduleEnum = {
  DEFERRED: "Deferred",
  PAY_AT_MATURITY: "Pay at maturity",
} as const;

export type ConvertibleInterestPaymentScheduleEnum = (typeof ConvertibleInterestPaymentScheduleEnum)[keyof typeof ConvertibleInterestPaymentScheduleEnum];

export const UpdateStatusEnum = {
  DRAFT: "Draft",
  PUBLIC: "Public",
  PRIVATE: "Private",
} as const;

export type UpdateStatusEnum = (typeof UpdateStatusEnum)[keyof typeof UpdateStatusEnum];
