ARG NODE_VERSION=20

# Alpine image
FROM node:${NODE_VERSION}-alpine AS alpine
FROM alpine AS dependencies
WORKDIR /app

# Copy dependencies
COPY . .

# Install dependencies
RUN npm i -g pnpm
RUN pnpm install

# Run the dev server
EXPOSE 3000
CMD [ "pnpm", "dev" ]
