name: "Build captable app"

runs:
  using: "composite"
  steps:
    - name: Copy env
      shell: bash
      run: cp .env.example .env

    - name: Build app
      shell: bash
      run: npm ci && npm run build
      env:
        SKIP_ENV_VALIDATION: 1
